config/routes.rb
Rails.application.routes.draw do
  root "tweets#index"

  get  "signup" => "users#new"
  post "users/create" => "users#create"
  get  "login" => "users#login_form"
  post "login" => "users#login"
  post "logout" => "users#logout"

  resources :tweets, only: [:index, :new, :create, :destroy]
  resources :likes, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :like_users, through: :likes, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tweets, dependent: :destroy
  has_one :profile, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_tweets, through: :likes, source: :tweet
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    tweet = Tweet.find(params[:tweet_id])
    user = User.find_by(id: session[:user_id])
    user.like_tweets << tweet
    redirect_to root_path
  end

  def destroy
    tweet = Tweet.find(params[:tweet_id])
    user = User.find_by(id: session[:user_id])
    like = tweet.likes.find_by(user_id: user.id)
    like.destroy if like
    redirect_to root_path
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    @profiles = Profile.all
  end

  def new
    @profile = Profile.new
  end

  def create
    user = User.find_by(id: session[:user_id])
    if user
      @profile = Profile.new(profile_params)
      @profile.user = user
      if @profile.save
        redirect_to profiles_path
      else
        render :new
      end
    else
      redirect_to login_path
    end
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])
    if @profile.update(profile_params)
      redirect_to profiles_path
    else
      render :edit
    end
  end

  private

  def profile_params
    params.require(:profile).permit(:name, :age, :location, :bio)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
    @user = User.find_by(id: session[:user_id])
  end

  def new
    @user = User.find_by(id: session[:user_id])
    redirect_to login_path if @user.nil?
  end

  def create
    user = User.find_by(id: session[:user_id])
    if user
      Tweet.create(message: params[:message], user_id: user.id)
      redirect_to root_path
    else
      redirect_to login_path
    end
  end

  def destroy
    tweet = Tweet.find_by(id: params[:id])
    if tweet && tweet.user_id == session[:user_id]
      tweet.destroy
    end
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(uid: params[:uid], password: params[:password])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def login_form; end

  def login
    user = User.find_by(uid: params[:uid])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      render :login_form
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "L5" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/likes/destroy.html.erb
<h1>Likes#destroy</h1>
<p>Find me in app/views/likes/destroy.html.erb</p>

app/views/profiles/create.html.erb
<h1>Profiles#create</h1>
<p>Find me in app/views/profiles/create.html.erb</p>

app/views/profiles/edit.html.erb
<h1>Profiles#edit</h1>
<p>Find me in app/views/profiles/edit.html.erb</p>

app/views/profiles/index.html.erb
<h2>プロフィール一覧</h2>
<%= link_to "新規作成", new_profile_path %><br>

<% @profiles.each do |p| %>
  <p>
    名前：<%= p.name %> / 年齢：<%= p.age %> / 地域：<%= p.location %><br>
    自己紹介：<%= p.bio %><br>
    <%= link_to "編集", edit_profile_path(p) %>
  </p>
<% end %>

app/views/profiles/new.html.erb
<h2>新しいプロフィール</h2>
<%= form_with model: @profile do |f| %>
  <p>名前：<%= f.text_field :name %></p>
  <p>年齢：<%= f.number_field :age %></p>
  <p>地域：<%= f.text_field :location %></p>
  <p>自己紹介：<%= f.text_area :bio %></p>
  <%= f.submit "登録" %>
<% end %>

app/views/profiles/update.html.erb
<h1>Profiles#update</h1>
<p>Find me in app/views/profiles/update.html.erb</p>

app/views/tweets/create.html.erb
<h1>Tweets#create</h1>
<p>Find me in app/views/tweets/create.html.erb</p>

app/views/tweets/destroy.html.erb
<h1>Tweets#destroy</h1>
<p>Find me in app/views/tweets/destroy.html.erb</p>

app/views/tweets/index.html.erb
<h2>ツイート一覧</h2>

<% if @user %>
  <%= form_with url: tweets_path do %>
    <%= text_field_tag :message %>
    <%= submit_tag "ツイート" %>
  <% end %>

  <%= link_to "新規追加", new_tweet_path, data: { turbo: false } %><br>
  <%= link_to "ログイン", login_path, data: { turbo: false } %><br>
  <%= link_to "ログアウト", logout_path, data: { turbo_method: :post } %><br>
  <p>ログイン中UID：<%= @user.uid %></p>
<% else %>
  <%= link_to "ログイン", login_path, data: { turbo: false } %><br>
  <%= link_to "ユーザ登録", signup_path, data: { turbo: false } %><br>
<% end %>

<hr>

<% @tweets.each do |tweet| %>
  <p>
    <%= tweet.message %> 
    <%= tweet.likes.count %> 
    <%= link_to "削除", tweet_path(tweet), data: { turbo_method: :delete } %>
    <% if @user %>
      <% if tweet.like_users.include?(@user) %>
        <%= link_to "いいね削除", likes_path(tweet_id: tweet.id), data: { turbo_method: :delete } %>
      <% else %>
        <%= link_to "いいね", likes_path(tweet_id: tweet.id), data: { turbo_method: :post } %>
      <% end %>
    <% end %>
  </p>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/login.html.erb
<h1>Users#login</h1>
<p>Find me in app/views/users/login.html.erb</p>

app/views/users/login_form.html.erb
<h2>ログイン</h2>

<%= form_with url: login_path do %>
  <p>
    ユーザーID：<%= text_field_tag :uid %>
  </p>
  <p>
    パスワード：<%= password_field_tag :password %>
  </p>
  <%= submit_tag "ログイン" %>
<% end %>

<p><%= link_to "ユーザ登録はこちら", signup_path %></p>

app/views/users/logout.html.erb
<h1>Users#logout</h1>
<p>Find me in app/views/users/logout.html.erb</p>

app/views/users/new.html.erb
<h2>ユーザ登録</h2>

<%= form_with url: "/users/create" do %>
  <p>
    ユーザーID：<%= text_field_tag :uid %>
  </p>
  <p>
    パスワード：<%= password_field_tag :password %>
  </p>
  <%= submit_tag "登録" %>
<% end %>

<p><%= link_to "ログイン画面へ戻る", login_path %></p>